stages:
  - test
  - build


unit:
  stage: test
  image: registry.gitlab.com/mbarkhau/pycalver/base:latest
  script:
    - make lint
    - make mypy
    - make test
  coverage: '/^(TOTAL|src).*?(\d+\%)$/'
  artifacts:
    paths:
      - htmlcov/
  allow_failure: false


pages:
  stage: build
  script:
    - mkdir -p public/cov
    - cp htmlcov/* public/cov/
  artifacts:
    paths:
      - public
  only:
  - master
