stages:
  - test
  - build


lint:
  stage: test
  image: registry.gitlab.com/mbarkhau/pycalver/base
  script:
    - make lint
    - make mypy
  artifacts:
    reports:
      junit:
        - reports/flake8.xml
    paths:
      - reports/mypycov/
  allow_failure: false


unit:
  # NOTE: Resource_group is conservative and can be disabled
  #    for simple tests. It should be enabled if the tests
  #    need exclusive access to some resource common external
  #    resource. This will prevent multiple pipelines from
  #    running concurrently.
  # resource_group: test-unit
  stage: test
  image: registry.gitlab.com/mbarkhau/pycalver/base
  script:
    - make test
    - make test_compat
  coverage: '/^(TOTAL|src).*?(\d+\%)$/'
  artifacts:
    reports:
      junit:
        - reports/pytest.xml
    paths:
      - reports/testcov/
  allow_failure: false


pages:
  stage: build
  script:
    - mkdir -p public/cov
    - mkdir -p public/mypycov
    - cp -r reports/testcov/* public/cov/
    - cp -r reports/mypycov/* public/mypycov/
  artifacts:
    paths:
      - public
  only:
    - master
